### ISSUE TITLE
combination of acceleration and acceleration_resampling

### ISSUE THREAD

**Issue by OkonSamuel** [alan-turing-institute/MLJTuning.jl#39]
@ablaom  Ok. I have had a look at the issue #15 and #14. Here are some of my concerns concerning the combination of `acceleration` and `acceleration_resampling` parameters.
All combinations  of those parameters seemed fine to me except.
1. `acceleration = CPUProcesses()` and `acceleration_resampling = CPUProcesses()`. In the same worker cores used in accelerating the tuning process is also the same used in accelerating the resampling process. This may result in slowdown. Depending on the case using either  (`acceleration = CPU1()` and `acceleration_resampling = CPUProcesses()`) or ( `acceleration = CPUProcesses()` and `acceleration_resampling = CPU1()`) would be better.
2. `acceleration = CPUThreads()` and `acceleration_resampling = CPUProcesses()`. (Same issue as in 1)
My suggestion would be to not allow uses use the above two case. 
Any Objections?

**Comment by ablaom** [comment]
Thanks for that valuable feedback. I agree something should be done about this. We could:

- A. Have `clean!(::TunedModel)` issue an informative warning for poor choices. Something like

```julia
"The combination acceleration=$acceration and acceleration_resampling=$acceleration_resampling is not generally optimal. You may want to consider ...."
```

- B.  Have `clean!` change the values to some better ones (probably distributing on the outer loop in A and reversing the choices in B) and we issue a warning stating what has been reset. 

While I can't really think of a use-case justifying A, I don't think we loose much in terms of convenience in going for this more flexible alternative. However, I don't have a strong opinion. 

@OkonSamuel If you're happy to make a PR, I am more than happy to support whatever you decide.
