### ISSUE TITLE
Score measure maximization double signal flip

### ISSUE THREAD

**Issue by cirocavani** [alan-turing-institute/MLJTuning.jl#87]
There is a double signal flip when optimizing for a score measure.

As I understand, lines 51-53 should be removed to fix score measure maximization in method `best(heuristic::NaiveSelection, history)`.

https://github.com/alan-turing-institute/MLJTuning.jl/blob/3e989d5e7d677d73b4c06d087f9a10c6fadcd511/src/selection_heuristics.jl#L46-L58

The first signal flip is done at line 50 (where `weights[1]` is negative from method `measure_adjusted_weights`) and then a second flip reverts the signal at line 53.

**Comment by ablaom** [comment]
Good catch! Looks like a bug.

**Comment by ablaom** [comment]
@cirocavani Thanks indeed for catching this serious bug. 

New patch release imminently.
